# http://blog.tgrrtt.com/exploring-the-travisci-configuration-file
# https://docs.travis-ci.com/user/build-stages
# https://github.com/mxcl/PromiseKit/blob/master/.travis.yml

os: osx
osx_image: xcode11.5
language: swift

cache:
  cocoapods: true
  directories: ["Carthage"]

env: DST='platform=macOS'

before_install: gem install cocoapods xcpretty
install:
  - swift package resolve
  - carthage bootstrap --no-use-binaries --cache-builds --platform macOS

before_script: set -exo pipefail
script:
  - swift test
  - xcodebuild -workspace "Slang.xcworkspace" -scheme "Slang-Test" -destination "$DST" build-for-testing test | xcpretty
  - pod lib lint
